export const ADD_INGREDIENT="ADD_INGREDIENT"
// export const ADD_INGREDIENT="ADD_INGREDIENT"\
export const REMOVE_INGREDIENT="REMOVE_INGREDIENT"

export const SET_INGREDIENT="SET_INGREDIENT"

export const PURCHASE_BURGER_SUCCESS="PURCHASE_BURGER_SUCCESS"
export const PURCHASE_BURGER_FAIL="PURCHASE_BURGER_FAIL"

export const purchaseBurgerStart="Purchase_Burger_Start"